export const repositories = [
  'cobraz/eaccounting',
  'cobraz/dynamodb-csv-convert',
  'cobraz/jira-config',
  'cobraz/norwegian-ssn-graphql-scalar',
  'cobraz/firestore-graphql-scalars',
  'cobraz/pubsub-http-handler',
  'cobraz/pulumi-wordpress',
  'cobraz/generate-runtypes',
  'cobraz/jsonschema-to-runtypes',
  'cobraz/protobuf-to-runtypes',
  'cobraz/svg-to-theme-ui-component',
  'cobraz/pulumi-gcp-scaffold',
  'cobraz/fiken-utils',

  'bjerkio/oidc-react',
  'bjerkio/tripletexjs',
  'bjerkio/unieconomy-js',
  'bjerkio/pulumi-appsync-modules',
  'bjerkio/crayon-api-js',
  'bjerkio/pulumi-sendgrid',
  'bjerkio/nestjs-oso',
  'bjerkio/fiken-js',

  'tabetalt/docusaurus-multiple-docs',
  'tabetalt/infra-config',
  'tabetalt/pulumix',
  'tabetalt/kit',
  'Oyatel/oyatel-sdk',

  'btoolsorg/apis',
];
