name: Pull Request
on:
  pull_request:

jobs:
  preview-changes:
    name: Preview changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node LTS
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: yarn

      - run: yarn install

      - uses: pulumi/actions@v5
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        with:
          command: preview
          refresh: true
          stack-name: prod
          comment-on-pr: true
